import {REACT_APP_FIREBASE_API_KEY, REACT_APP_FIREBASE_AUTH_DOMAIN,
        REACT_APP_FIREBASE_PROJECT_ID, REACT_APP_FIREBASE_STORAGE_BUCKET,
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID, REACT_APP_FIREBASE_APP_ID,
        REACT_APP_ANDROID_KEY, REACT_APP_EXPO_ID} from "react-native-dotenv";

const FIREBASE_CONFIG = {
    apiKey: REACT_APP_FIREBASE_API_KEY,
    authDomain: REACT_APP_FIREBASE_AUTH_DOMAIN,
    projectId: REACT_APP_FIREBASE_PROJECT_ID,
    storageBucket: REACT_APP_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
    appId: REACT_APP_FIREBASE_APP_ID
};

const EXPO_ID = REACT_APP_EXPO_ID;

const ANDROID_ID = REACT_APP_ANDROID_KEY;

export {
    FIREBASE_CONFIG, EXPO_ID, ANDROID_ID
};
